In [12]:
import numpy as np

a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a)
print(a[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12

In [13]:
import pandas as pd

# Define a dictionary containing employee data
data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32]}

# Define a dictionary containing employee data
data2 = {'key': ['K1', 'K2', 'K3', 'K4'],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannauj'],
         'Qualification': ['Btech', 'B.A', 'Bcom', 'B.hons']}

# Convert the dictionary into DataFrame
df = pd.DataFrame(data1)
# Convert the dictionary into DataFrame
df1 = pd.DataFrame(data2)
print(df, "\n\n", df1)

  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

   key    Address Qualification
0  K1     Nagpur         Btech
1  K2     Kanpur           B.A
2  K3  Allahabad          Bcom
3  K4    Kannauj        B.hons

In [14]:
import pandas as pd
import numpy as np
# creating a sample dataframe
data = pd.DataFrame({'Brand': ['Maruti', 'Hyundai', 'Tata',
'Mahindra', 'Maruti', 'Hyundai',
'Renault', 'Tata', 'Maruti'],
'Year': [2012, 2014, 2011, 2015, 2012,
2016, 2014, 2018, 2019],
'Kms Driven': [50000, 30000, 60000,
25000, 10000, 46000,
31000, 15000, 12000],
'City': ['Gurgaon', np.nan, 'Mumbai',
'Delhi', 'Mumbai', 'Delhi',
'Mumbai', 'Chennai', 'Ghaziabad'],
'Mileage': [28, 27, 25, 26, 28,
29, 24, 21, 24]})
# displaying the DataFrame
display(data)
#data.isnull()

      Brand  Year  Kms Driven       City  Mileage
0    Maruti  2012       50000    Gurgaon       28
1   Hyundai  2014       30000        NaN       27
2      Tata  2011       60000     Mumbai       25
3  Mahindra  2015       25000      Delhi       26
4    Maruti  2012       10000     Mumbai       28
5   Hyundai  2016       46000      Delhi       29
6   Renault  2014       31000     Mumbai       24
7      Tata  2018       15000    Chennai       21
8    Maruti  2019       12000  Ghaziabad       24