In [2]:
# -*- coding: utf-8 -*-
# Import necessary libraries
import pandas as pd
import numpy as np
from google.colab import files

# Upload file from local system
uploaded = files.upload()
# Get the filename of the uploaded file
filename = list(uploaded.keys())[0]

# Read the uploaded CSV file using pandas
df = pd.read_csv(filename)

# Display first and last rows of the dataframe
print("First 10 rows:")
print(df.head(10))

print("\nLast 10 rows:")
print(df.tail(10))

# Information about the dataframe
print("\nDataFrame Info:")
print(df.info())

# Selecting specific rows and columns using iloc and loc
print("\nSelect specific data using iloc:")
print(df.iloc[2, 3])  # Selects 3rd row and 4th column (0-indexed)
print(df.iloc[:, 1])  # Selects all rows in the 2nd column
print(df.iloc[1:3, 0:2])  # Selects rows 2-3 and columns 1-2

print("\nSelect specific data using loc:")
print(df.loc[2, 'First Name'])  # Selects row label 2 in 'First Name' column
print(df.loc[:, 'Email'])  # Selects all rows in the 'Email' column
print(df.loc[1:3, 'First Name':'Company'])  # Selects rows 1 to 3 (inclusive)

# Handling missing values
print("\nChecking for missing values:")
print(df.isnull().sum())  # Count missing values per column
df.fillna("Unknown", inplace=True)  # Replace missing values with "Unknown"

# Dropping unnecessary columns
df.drop(columns=['Phone 2'], axis=1, inplace=True)

# Filtering data based on conditions
print("\nFiltering data where 'First Name' is 'Sheryl':")
data_sheryl = df[df['First Name'] == 'Sheryl']
print(data_sheryl)

# Selecting multiple specific rows using iloc
print("\nSelecting rows with indices 1, 3, 5, and 6:")
print(df.iloc[[1, 3, 5, 6]])

# Filter rows based on multiple conditions
filtered_data = df.loc[(df['Company'] == 'Steele Group') & (df['City'] == 'East Leonard')]
print("\nFiltered data where Company is 'Steele Group' and City is 'East Leonard':")
print(filtered_data)

# Displaying statistical summary
print("\nStatistical summary of numerical columns:")
print(df.describe())

# Sorting data based on a column
df_sorted = df.sort_values(by="Subscription Date", ascending=True)
print("\nSorted DataFrame by Subscription Date:")
print(df_sorted.head())

# Handling duplicate values
df.drop_duplicates(inplace=True)

# Merging two datasets
employees = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "Department": ["Sales", "HR", "IT"]
})

salaries = pd.DataFrame({
    "ID": [1, 2, 3],
    "Salary": [50000, 60000, 70000]
})

# Perform inner join on 'ID'
merged_df = employees.merge(salaries, how="inner", on="ID")
print("\nMerged DataFrame on 'ID':")
print(merged_df)

# Performing left join
left_join_df = employees.merge(salaries, how="left", on="ID")
print("\nLeft Join DataFrame:")
print(left_join_df)

# Resetting index and performing join operation
employees.set_index("ID", inplace=True)
salaries.set_index("ID", inplace=True)

joined_df = employees.join(salaries, how="inner")
print("\nJoined DataFrame using index:")
print(joined_df)

# Filtering data based on values
print("\nFiltering cars with brand 'Maruti' and Mileage > 25:")
data = pd.DataFrame({
    'Brand': ['Maruti', 'Hyundai', 'Tata', 'Mahindra', 'Maruti'],
    'Year': [2012, 2014, 2011, 2015, 2019],
    'Kms Driven': [50000, 30000, 60000, 25000, 12000],
    'City': ['Gurgaon', 'Delhi', 'Mumbai', 'Delhi', 'Chennai'],
    'Mileage': [28, 27, 25, 26, 29]
})
filtered_cars = data.loc[(data['Brand'] == 'Maruti') & (data['Mileage'] > 25)]
print(filtered_cars)

# Updating values based on condition
data.loc[data['Year'] < 2015, 'Mileage'] = 30
print("\nUpdated Mileage for cars manufactured before 2015:")
print(data)

# Export the processed dataframe to CSV
df.to_csv("processed_data.csv", index=False)
print("\nProcessed data saved to 'processed_data.csv'")

Saving customers-100.csv to customers-100.csv
First 10 rows:
   Index      Customer Id First Name  Last Name  \
0      1  DD37Cf93aecA6Dc     Sheryl     Baxter
1      2  1Ef7b82A4CAAD10    Preston     Lozano
2      3  6F94879bDAfE5a6        Roy      Berry
3      4  5Cef8BFA16c5e3c      Linda      Olsen
4      5  053d585Ab6b3159     Joanna     Bender
5      6  2d08FB17EE273F4      Aimee      Downs
6      7  EA4d384DfDbBf77     Darren       Peck
7      8  0e04AFde9f225dE      Brett     Mullen
8      9  C2dE4dEEc489ae0     Sheryl     Meyers
9     10  8C2811a503C7c5a   Michelle  Gallagher

                           Company               City  \
0                  Rasmussen Group       East Leonard
1                      Vega-Gentry  East Jimmychester
2                    Murillo-Perry      Isabelborough
3  Dominguez, Mcmillan and Donovan         Bensonview
4         Martin, Lang and Andrade     West Priscilla
5                     Steele Group      Chavezborough
6     Lester, Woodard and Mitchell           Lake Ana
7     Sanford, Davenport and Giles            Kimport
8                   Browning-Simon       Robersonstad
9                     Beck-Hendrix         Elaineberg

                      Country                 Phone 1                Phone 2  \
0                       Chile            229.077.5154       397.884.0519x718
1                    Djibouti              5153435776       686-620-1820x944
2         Antigua and Barbuda         +1-539-402-0259    (496)978-3969x58947
3          Dominican Republic  001-808-617-6467x12895        +1-813-324-8756
4  Slovakia (Slovak Republic)  001-234-203-0635x76146  001-199-446-3860x3486
5      Bosnia and Herzegovina     (283)437-3886x88321           999-728-1637
6            Pitcairn Islands      (496)452-6181x3291   +1-247-266-0963x4995
7                    Bulgaria    001-583-352-7197x297       001-333-145-0369
8                      Cyprus       854-138-4911x5772    +1-448-910-2276x729
9                 Timor-Leste        739.218.2516x459   001-054-401-0347x617

                         Email Subscription Date                      Website
0     zunigavanessa@smith.info        2020-08-24   http://www.stephenson.com/
1              vmata@colon.com        2021-04-23        http://www.hobbs.com/
2          beckycarr@hogan.com        2020-03-25     http://www.lawrence.com/
3  stanleyblackwell@benson.org        2020-06-02   http://www.good-lyons.com/
4      colinalvarado@miles.net        2021-04-17  https://goodwin-ingram.com/
5          louis27@gilbert.com        2020-02-25       http://www.berger.net/
6          tgates@cantrell.com        2021-08-24          https://www.le.com/
7              asnow@colon.com        2021-04-12  https://hammond-ramsey.com/
8      mariokhan@ryan-pope.org        2020-01-13     https://www.bullock.net/
9            mdyer@escobar.net        2021-11-08           https://arias.com/

Last 10 rows:
    Index      Customer Id First Name Last Name                      Company  \
90     91  5ef6d3eefdD43bE       Nina    Chavez                Byrd-Campbell
91     92  98b3aeDcC3B9FF3      Shane     Foley                   Rocha-Hart
92     93  aAb6AFc7AfD0fF3     Collin     Ayers                Lamb-Peterson
93     94  54B5B5Fe9F1B6C5     Sherry     Young      Lee, Lucero and Johnson
94     95  BE91A0bdcA49Bbc    Darrell   Douglas  Newton, Petersen and Mathis
95     96  cb8E23e48d22Eae       Karl     Greer                    Carey LLC
96     97  CeD220bdAaCfaDf       Lynn  Atkinson        Ware, Burns and Oneal
97     98  28CDbC0dFe4b1Db       Fred    Guerra                Schmitt-Jones
98     99  c23d1D9EE8DEB0A     Yvonne    Farmer           Fitzgerald-Harrell
99    100  2354a0E336A91A1   Clarence    Haynes           Le, Nash and Cross

                City          Country                Phone 1  \
90    Cassidychester           Bhutan           053-344-3205
91  South Dannymouth          Hungary        +1-822-569-0302
92      South Lonnie         Anguilla       404-645-5351x012
93      Frankchester  Solomon Islands           158-687-1764
94      Daisyborough             Mali  001-084-845-9524x1777
95      East Richard           Guyana    (188)169-1674x58692
96      New Bradview        Sri Lanka        +1-846-706-2218
97        Ortegaland  Solomon Islands   +1-753-067-8419x7170
98   Lake Elijahview            Aruba          (530)311-9786
99         Judymouth         Honduras          (753)813-6941

                   Phone 2                           Email Subscription Date  \
90     +1-330-920-5422x571            elliserica@frank.com        2020-03-26
91  001-626-114-5844x55073              nsteele@sparks.com        2021-07-06
92   001-257-582-8850x8516        dudleyemily@gonzales.biz        2021-06-29
93       (438)375-6207x003     alan79@gates-mclaughlin.com        2021-04-04
94        001-769-564-6303        grayjean@lowery-good.com        2022-02-17
95    001-841-293-3519x614                hhart@jensen.com        2022-01-30
96            605.413.3198               vkemp@ferrell.com        2021-07-10
97   +1-632-666-7507x92121                swagner@kane.org        2021-09-18
98  001-869-452-0943x12424  mccarthystephen@horn-green.biz        2021-08-11
99            783.639.1472          colleen91@faulkner.biz        2020-03-11

                              Website
90              https://www.pugh.com/
91       https://www.holt-sparks.com/
92               http://www.ruiz.com/
93                https://travis.net/
94                 https://banks.biz/
95            http://hayes-perez.com/
96         https://novak-allison.com/
97              https://www.ross.com/
98               http://watkins.info/
99  http://www.hatfield-saunders.net/

DataFrame Info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Index              100 non-null    int64
 1   Customer Id        100 non-null    object
 2   First Name         100 non-null    object
 3   Last Name          100 non-null    object
 4   Company            100 non-null    object
 5   City               100 non-null    object
 6   Country            100 non-null    object
 7   Phone 1            100 non-null    object
 8   Phone 2            100 non-null    object
 9   Email              100 non-null    object
 10  Subscription Date  100 non-null    object
 11  Website            100 non-null    object
dtypes: int64(1), object(11)
memory usage: 9.5+ KB
None

Select specific data using iloc:
Berry
0     DD37Cf93aecA6Dc
1     1Ef7b82A4CAAD10
2     6F94879bDAfE5a6
3     5Cef8BFA16c5e3c
4     053d585Ab6b3159
           ...
95    cb8E23e48d22Eae
96    CeD220bdAaCfaDf
97    28CDbC0dFe4b1Db
98    c23d1D9EE8DEB0A
99    2354a0E336A91A1
Name: Customer Id, Length: 100, dtype: object
   Index      Customer Id
1      2  1Ef7b82A4CAAD10
2      3  6F94879bDAfE5a6

Select specific data using loc:
Roy
0           zunigavanessa@smith.info
1                    vmata@colon.com
2                beckycarr@hogan.com
3        stanleyblackwell@benson.org
4            colinalvarado@miles.net
                   ...
95                  hhart@jensen.com
96                 vkemp@ferrell.com
97                  swagner@kane.org
98    mccarthystephen@horn-green.biz
99            colleen91@faulkner.biz
Name: Email, Length: 100, dtype: object
  First Name Last Name                          Company
1    Preston    Lozano                      Vega-Gentry
2        Roy     Berry                    Murillo-Perry
3      Linda     Olsen  Dominguez, Mcmillan and Donovan

Checking for missing values:
Index                0
Customer Id          0
First Name           0
Last Name            0
Company              0
City                 0
Country              0
Phone 1              0
Phone 2              0
Email                0
Subscription Date    0
Website              0
dtype: int64

Filtering data where 'First Name' is 'Sheryl':
   Index      Customer Id First Name Last Name          Company          City  \
0      1  DD37Cf93aecA6Dc     Sheryl    Baxter  Rasmussen Group  East Leonard
8      9  C2dE4dEEc489ae0     Sheryl    Meyers   Browning-Simon  Robersonstad

  Country            Phone 1                     Email Subscription Date  \
0   Chile       229.077.5154  zunigavanessa@smith.info        2020-08-24
8  Cyprus  854-138-4911x5772   mariokhan@ryan-pope.org        2020-01-13

                      Website
0  http://www.stephenson.com/
8    https://www.bullock.net/

Selecting rows with indices 1, 3, 5, and 6:
   Index      Customer Id First Name Last Name  \
1      2  1Ef7b82A4CAAD10    Preston    Lozano
3      4  5Cef8BFA16c5e3c      Linda     Olsen
5      6  2d08FB17EE273F4      Aimee     Downs
6      7  EA4d384DfDbBf77     Darren      Peck

                           Company               City                 Country  \
1                      Vega-Gentry  East Jimmychester                Djibouti
3  Dominguez, Mcmillan and Donovan         Bensonview      Dominican Republic
5                     Steele Group      Chavezborough  Bosnia and Herzegovina
6     Lester, Woodard and Mitchell           Lake Ana        Pitcairn Islands

                  Phone 1                        Email Subscription Date  \
1              5153435776              vmata@colon.com        2021-04-23
3  001-808-617-6467x12895  stanleyblackwell@benson.org        2020-06-02
5     (283)437-3886x88321          louis27@gilbert.com        2020-02-25
6      (496)452-6181x3291          tgates@cantrell.com        2021-08-24

                      Website
1       http://www.hobbs.com/
3  http://www.good-lyons.com/
5      http://www.berger.net/
6         https://www.le.com/

Filtered data where Company is 'Steele Group' and City is 'East Leonard':
Empty DataFrame
Columns: [Index, Customer Id, First Name, Last Name, Company, City, Country, Phone 1, Email, Subscription Date, Website]
Index: []

Statistical summary of numerical columns:
            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

Sorted DataFrame by Subscription Date:
    Index      Customer Id First Name Last Name                     Company  \
8       9  C2dE4dEEc489ae0     Sheryl    Meyers              Browning-Simon
66     67  2A13F74EAa7DA6c    Makayla    Cannon               Henderson Inc
69     70  CC68FD1D3Bbbf22      Riley      Good                    Wade PLC
73     74  A3F76Be153Df4a3      Anita    Benson                 Parrish Ltd
84     85  03A1E62ADdeb31c      Corey      Holt  Mcdonald, Bird and Ramirez

            City             Country                 Phone 1  \
8   Robersonstad              Cyprus       854-138-4911x5772
66    Georgeport       New Caledonia  001-215-801-6392x46009
69    Erikaville              Canada              6977745822
73   Skinnerport  Russian Federation      874.617.5668x69878
84    New Glenda                Fiji   001-439-242-4986x7918

                      Email Subscription Date                    Website
8   mariokhan@ryan-pope.org        2020-01-13   https://www.bullock.net/
66   scottcurtis@hurley.biz        2020-01-20  http://www.velazquez.net/
69      alex06@galloway.com        2020-02-03         http://conway.org/
73     angie04@oconnell.com        2020-02-09        http://oconnor.com/
84     maurice46@morgan.com        2020-02-18     http://www.watson.com/

Merged DataFrame on 'ID':
   ID     Name Department  Salary
0   1    Alice      Sales   50000
1   2      Bob         HR   60000
2   3  Charlie         IT   70000

Left Join DataFrame:
   ID     Name Department  Salary
0   1    Alice      Sales   50000
1   2      Bob         HR   60000
2   3  Charlie         IT   70000

Joined DataFrame using index:
       Name Department  Salary
ID
1     Alice      Sales   50000
2       Bob         HR   60000
3   Charlie         IT   70000

Filtering cars with brand 'Maruti' and Mileage > 25:
    Brand  Year  Kms Driven     City  Mileage
0  Maruti  2012       50000  Gurgaon       28
4  Maruti  2019       12000  Chennai       29

Updated Mileage for cars manufactured before 2015:
      Brand  Year  Kms Driven     City  Mileage
0    Maruti  2012       50000  Gurgaon       30
1   Hyundai  2014       30000    Delhi       30
2      Tata  2011       60000   Mumbai       30
3  Mahindra  2015       25000    Delhi       26
4    Maruti  2019       12000  Chennai       29

Processed data saved to 'processed_data.csv'

In [15]:
#create a dataframe
import pandas as pd
sales_data = {
    'TransactionID': [1, 2, 3, 4, 5],
    'CustomerID': [101, 102, 103, 104, 101],
    'Amount': [250, 300, 400, 500, 600],
    'Date': ['2025-01-01', '2025-01-02', '2025-01-03', '2025-01-04', '2025-01-05']
}
#create a customer dataframe as sales_data
customer_data={
    'CustomerID':[101,102,103,104],
    'CustomerName':['John','Jane','Bob','Alice'],
    'Age':[25,30,35,40],
    'Location':['New York','Los Angeles','Chicago','San Francisco']
}
sales_data = pd.DataFrame(sales_data)
customer_data = pd.DataFrame(customer_data)

#show basic structure of sales_df
print("Sales Data:")
print(sales_data.head())

#show basic structure of customer_df
print("\nCustomer Data:")
print(customer_data.head())

#

Sales Data:
   TransactionID  CustomerID  Amount        Date
0              1         101     250  2025-01-01
1              2         102     300  2025-01-02
2              3         103     400  2025-01-03
3              4         104     500  2025-01-04
4              5         101     600  2025-01-05

Customer Data:
   CustomerID CustomerName  Age       Location
0         101         John   25       New York
1         102         Jane   30    Los Angeles
2         103          Bob   35        Chicago
3         104        Alice   40  San Francisco

Merged Data:
   TransactionID  CustomerID  Amount        Date CustomerName  Age  \
0              1         101     250  2025-01-01         John   25
1              2         102     300  2025-01-02         Jane   30
2              3         103     400  2025-01-03          Bob   35
3              4         104     500  2025-01-04        Alice   40
4              5         101     600  2025-01-05         John   25

        Location
0       New York
1    Los Angeles
2        Chicago
3  San Francisco
4       New York