In [8]:
#normalization
#with min max scaler
from sklearn.preprocessing import MinMaxScaler
import pandas as pd

#sample dataset with multiple features
data = {
    'Age': [25, 30, 35, 40],
    'Income': [50000, 60000, 70000, 80000],
    'height': [160, 170, 180, 190],
    'weight': [60, 70, 80, 90]
}

df = pd.DataFrame(data)
print(df)

#initialize minmaxscaler
scaler = MinMaxScaler()

#normalize the dataset
normalized_data = scaler.fit_transform(df)

#create a new dataframe with the normalized values
normalized_df = pd.DataFrame(normalized_data, columns=df.columns)
print("\nNormalize DataFrame (scales to range [0,1]): ")
print(normalized_df)

   Age  Income  height  weight
0   25   50000     160      60
1   30   60000     170      70
2   35   70000     180      80
3   40   80000     190      90

Normalize DataFrame (scales to range [0,1]):
        Age    Income    height    weight
0  0.000000  0.000000  0.000000  0.000000
1  0.333333  0.333333  0.333333  0.333333
2  0.666667  0.666667  0.666667  0.666667
3  1.000000  1.000000  1.000000  1.000000

In [9]:
#standardization
from sklearn.preprocessing import StandardScaler
import pandas as pd

#sample dataset with different features
data={
    'Age': [25,30,45,50,28,36],
    'Income': [50000,60000,70000,80000,55000,65000]
}

df = pd.DataFrame(data)
print(df)

#initialize standardization with data
scaler = StandardScaler()

#standardize the dataset
standardized_data = scaler.fit_transform(df)

#create a new dataframe with the standardized values
standardized_df = pd.DataFrame(standardized_data, columns=df.columns)
print("\nStandardized DataFrame: ")
print(standardized_df)

   Age  Income
0   25   50000
1   30   60000
2   45   70000
3   50   80000
4   28   55000
5   36   65000

Standardized DataFrame:
        Age    Income
0 -1.171603 -1.352247
1 -0.622414 -0.338062
2  1.025153  0.676123
3  1.574342  1.690309
4 -0.842090 -0.845154
5  0.036613  0.169031